name: "Nix CI"

on:
    push:
    pull_request: 
    workflow_dispatch:  
    workflow_run:
        workflows: ["Chores"]
        types: [completed]

jobs: 
    nix-ci:
        uses: KestrelsDevelopment/Workflows/.github/workflows/nix-ci.yml@main 
